[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "NODE_OPTIONS=--max-old-space-size=460 npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:clear"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host 0.0.0.0 --port $PORT"